management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

weyland:
  audit:
    mode: HYBRID
    default-topic: android-commands-audit

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer